shellPort : 1336
masterPort : 1337
workerPort : 1338 #make sure port range <workerPort> + <workerPort + numExecutorsPerServer > are free
apiPort : 1335
masterServer : "127.0.0.1"
numExecutorsPerServer  : 4
